---
- name: create ssh config directory
  file:
    path: ~/.ssh
    state: directory
    owner: "{{ roles_common_deploy_user }}"
    group: "{{ roles_common_deploy_user }}"
    mode: 0700
  become_user: "{{ roles_common_deploy_user }}"

- name: get home directory of deploy user
  command: pwd
  args:
    chdir: "~"
  become_user: "{{ roles_common_deploy_user }}"
  register: result_command_pwd

- name: set aws cli path
  set_fact:
    path_aws_cli: "{{ '' if ansible_distribution == 'Amazon' else '/opt/pyenv/shims/' }}"

- name: download deploy key
  command: "{{ path_aws_cli }}aws s3 cp s3://{{ ssh_config_git_deploy_key_s3_bucket_name }}/{{ item }} {{ result_command_pwd.stdout }}/.ssh/{{ item }}"
  args:
    creates: "{{ result_command_pwd.stdout }}/.ssh/{{ item }}"
  with_items: "{{ ssh_config_git_deploy_key_names }}"

- name: set permission for deploy key
  file:
    path: "{{ result_command_pwd.stdout }}/.ssh/{{ item }}"
    owner: "{{ roles_common_deploy_user }}"
    group: "{{ roles_common_deploy_user }}"
    mode: 0600
  with_items: "{{ ssh_config_git_deploy_key_names }}"

- name: set ssh config
  template:
    src: config.j2
    dest: ~/.ssh/config
    owner: "{{ roles_common_deploy_user }}"
    group: "{{ roles_common_deploy_user }}"
    mode: 0600
  become_user: "{{ roles_common_deploy_user }}"